site_name: Moiz Kawar's Profile
site_description: A showcase of my projects, skills, and experience in software and chatbot development.
site_author: Moiz
site_url: https://moizkhawar.github.io/mk.portfolio/
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.annotate
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Projects: projects.md
  - Skills: skills.md
  - Blog: blogs.md
  - About Me: about.md
  - Contact: contact.md
  

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - markdownextradata
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - footnotes
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/moizkhawar
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/moiz-kawar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourhandle
  copyright:
    text: "© 2025 Moiz Khawar. All rights reserved."
